#!/bin/bash
clear

# Mostra o cabeçalho
echo '·▄▄▄▄•▪   ▄▄▄· ▄▄▄· ▄· ▄▌.▄▄ ·  ▄ .▄ ▄▄▄· ▄▄▄  ▄▄▄ .'
echo '▪▀·.█▌██ ▐█ ▄█▐█ ▄█▐█▪██▌▐█ ▀. ██▪▐█▐█ ▀█ ▀▄ █·▀▄.▀·'
echo '▄█▀▀▀•▐█· ██▀· ██▀·▐█▌▐█▪▄▀▀▀█▄██▀▐█▄█▀▀█ ▐▀▀▄ ▐▀▀▪▄'
echo '█▌▪▄█▀▐█▌▐█▪·•▐█▪·• ▐█▀·.▐█▄▪▐███▌▐▀▐█ ▪▐▌▐█•█▌▐█▄▄▌'
echo '·▀▀▀ •▀▀▀.▀   .▀     ▀ •  ▀▀▀▀ ▀▀▀ · ▀  ▀ .▀  ▀ ▀▀▀'
echo '·▄▄▄▄        ▄▄▌ ▐ ▄▌ ▐ ▄ ▄▄▌         ▄▄▄· ·▄▄▄▄  ▄▄▄ .▄▄▄'
echo '██▪ ██ ▪     ██· █▌▐█•█▌▐███•  ▪     ▐█ ▀█ ██▪ ██ ▀▄.▀·▀▄ █·'
echo '▐█· ▐█▌ ▄█▀▄ ██▪▐█▐▐▌▐█▐▐▌██▪   ▄█▀▄ ▄█▀▀█ ▐█· ▐█▌▐▀▀▪▄▐▀▀▄'
echo '██. ██ ▐█▌.▐▌▐█▌██▐█▌██▐█▌▐█▌▐▌▐█▌.▐▌▐█ ▪▐▌██. ██ ▐█▄▄▌▐█•█▌'
echo '▀▀▀▀▀•  ▀█▄▀▪ ▀▀▀▀ ▀▪▀▀ █▪.▀▀▀  ▀█▄▀▪ ▀  ▀ ▀▀▀▀▀•  ▀▀▀ .▀  ▀'
echo 'Email: victor.oliveira@gmx.com'
echo ''

# Lê a url do site:
echo '*** Digite a URL do site Zippyshare: ***'
read -p '>>> ' URL

# Armazena a variável B e realiza a soma
VARB=`curl -s $URL|grep 'var b'|cut -d ' ' -f8|rev|cut -d ';' -f2|rev`
VARB=$((VARB+6))

# Armazena o nome do arquivo
FN=`curl -s $URL|grep 'twitter:title'|cut -d '"' -f4`

# Modifica o "v" por "d"
URL=`echo $URL|sed 's:com/v:com/d:'`

# Armazena o ID do download
ID=`echo $URL|cut -d '/' -f3`

# Armazena a base da URL
BASE_URL=`echo $URL|cut -d '/' -f1-3`

# Cria a versão final do link
FINAL_URL=`echo ''"$BASE_URL"'/'"$VARB"'3/'"$FN"''`

# Mostra a URL de download
echo ''
echo '*** A URL de download é: ***'
echo $FINAL_URL
echo ''
echo 'Iniciando download...'
echo ''

wget -q --show-progress -O "$FN" "$FINAL_URL" && echo ''; echo 'Download Concluído!'; echo ''; echo "Arquivo salvo na pasta: $PWD"; echo ''
